apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 3800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: susguzman/bootcamp-back:0.1.0
        env:
          - name: POSTGRE_HOST
            value: postgres-service
          - name: POSTGRE_PASS
            valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3800
